config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # get 'sessions/new'

  # get 'sessions/create'

  # get 'sessions/destroy'
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    root 'stpre#index', as: 'stpre_index', via: :all
  end

  resources :keduas
  resources :products do
    get :who_bought, on: :member
  end

  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_product(product)
		current_item = line_items.find_by(product_id: product.id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product.id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

end

app/models/kedua.rb
class Kedua < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true
  	belongs_to :product, optional: true
  	belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items, dependent: :destroy
	enum pay_type: {
		"Check" 	  		=> 0,
		"Check card"  		=> 1,
		"Purchase order"	=> 2
	}

	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: pay_types.keys

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_then_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(png|jpg|gif)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image . '
	}

	private
	def ensure_not_referenced_by_any_line_item
		unless line_items.empty?
			errors.add(:base, 'Line Items present')
			throw :abort
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
	after_destroy :ensure_an_admin_remains
	validates :name, presence: true, uniqueness: true
	has_secure_password

	# class Error < standardError
		
	# end

	private
		def ensure_an_admin_remains
			if User.count.zero?
				raise Error.new "Can't delete last user"
			end
		end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/keduas_helper.rb
module KeduasHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stpre_helper.rb
module StpreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

<p>
	It's <%= Time.now %>.
	We have <%= pluralize(@total_orders, "order") %>
</p>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html> -->
<html>
  <head>
    <title>Pragrog Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= csrf_meta_tags %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>

  <body class='<%= controller.controller_name %>'>
  <div id="banner">
  <%= form_tag stpre_index_path, class: 'locale' do %>
    <%= select_tag 'set_locale',
      options_for_select(LANGUAGES, I18n.locale.to_s),
      onChange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
  <% end %>
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <span class="title"><%= @page_title %></span>
  </div>
  <div id="columns">
	  <div id="side">
      <div id="cart">
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>  
          <% end %>
        <% end %>
      </div>
      
	  	<ul>
	  		<li><a href="http://www...."><%= t('.home') %></a></li>
	  		<li><a href="http://www...."><%= t('.question') %></a></li>
	  		<li><a href="http://www...."><%= t('.news') %></a></li>
	  		<li><a href="http://www...."><%= t('.contact') %></a></li>
	  	</ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>
	  </div>
	  <div id="main">
	  	<%= yield %>
	  </div>
  </div>
  </body>
</html>